### PR TITLE
Add Cmake Closes #110

### LINKED ISSUE #110: Add cmake support
Not necessarily needed with Qt 6, but nice to have cmake support in future

### PR DESCRIPTION
**Pull request by Lasall**
- Targets Linux only.
 - For CMake simplifications I changed variable name `___PREFIX___` in man .in files to `@___PREFIX___@` and adjusted the Makefile
 - I tried to stay as close as possible to to pro/pri files.
 - There is a third party file `cmake/FindHUNSPELL.cmake` included which is BSD-3 licenced.
 - Adding support for different platforms should be fairly easy. I don't have access to macOS but at work I use https://github.com/leetal/ios-cmake. Then apart from installation instructions https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_BUNDLE_INFO_PLIST.html has to be set for the APPLE platform.
 - I noticed there were two variables to change the build/install process: community and PREVIEW. For CMake those can be configured during configure process with: `cmake -DPREVIEW=abc -DCOMMUNITY=xyz`

I didn't compare the (Linux) compiler flags with qmake. The CMake compile instructions can be generated with the option `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` which generates a file `compile_commands.json`.

Following steps will configure and build the project (change Qt install path and any make options accordingly):
```bash
cmake -B build-cmake -DCMAKE_PREFIX_PATH=/opt/Qt/5.15.2/gcc_64
cmake --build build-cmake -- -j8
sudo cmake --install build-cmake  # or DESTDIR=foobar cmake --install build-cmake
```

### CODE REVIEW

**Comment by ElTh0r0** [comment]
Many thanks @Lasall 
I'll need some time before merging it - not because I don't trust you that it is working as expected, but I want to (try to) understand the provided cmake setup and do some tests since I never used cmake before :)

**Comment by Lasall** [comment]
No worries, on the way you can maybe add the missing macOS instructions. I might find some time next week to add missing Windows instructions. Will also compare the build instructions (compile_commands.json) to make sure the compiler invocations are the same.
Does InyokaEdit generally work with Qt6? If so we could add an option for Qt6.

**Comment by ElTh0r0** [comment]
Yes Qt6 is working!
There are only two things to be considered:
- QWebEngineView is not available for Qt6 yet (should be available with Qt 6.2), so the editor has to be compiled without preview.
- Spellchecker plugin needs "core5compat" if compiled with Qt6:
https://github.com/inyokaproject/inyokaedit/blob/21899d48bdd425a0d5b4fd8b022881b9cec71fa9/plugins/spellchecker/spellchecker.pro#L64

**Comment by ElTh0r0** [comment]
It took me longer than expected to find time to test it. In the end testing was quite easy, but for sure I would not have been able to write the cmake files myself! One more time: Many thanks Lasall!

**Pull request merged**
